In [2]:
import requests
import pandas as pd
API_KEY= 'AIzaSyCHdEgk1wpQtlaY2XJk3kBbh4cqyPNzlMA'

search_url= "https://www.googleapis.com/youtube/v3/search"

search_params={
    "part":"snippet",
    "q":"川越",
    "videoCategoryId":19,
    "type":"video",
    "key":API_KEY,
    "relevanceLanguage": "zh",
    "maxResults":50

}
page_token=None
videos=[]
for i in range(10):
 if page_token:
        search_params["pageToken"] = page_token
 response=requests.get(search_url,params=search_params)
 data=response.json()

 video_ids=[]

 for video in data["items"]:
  video_id=video["id"]["videoId"]
  video_ids.append(video_id)

 video_url = "https://www.googleapis.com/youtube/v3/videos"

 video_params={
    "part":"snippet,statistics",
    "id":",".join(video_ids),
    "key":API_KEY
}

 response=requests.get(video_url,params=video_params)
 data_videos=response.json()



 for video in data_videos["items"]:
  video_id=video["id"]

  title=video["snippet"]["title"]
  published_at = video["snippet"]["publishedAt"]
  description= video["snippet"]["description"]
  tags1=video["snippet"].get("tags",[])
  tags=",".join(tags1)

  views = int(video["statistics"].get("viewCount",0))
  likes = int(video["statistics"].get("likeCount",0))
  comments = int(video["statistics"].get("commentCount",0))

  videos.append({
        "video_id": video_id,
        "title": title,
        "description":description,
        "tags":tags,
        "published_at": published_at,
        "views": views,
        "likes": likes,
        "comments": comments
    })
 page_token = data.get("nextPageToken")


df = pd.DataFrame(videos)
df = df.drop_duplicates(subset="video_id")
print("\n===== YouTube動画データ =====")
df["like_rate"] = df["likes"] / df["views"] * 100
df["comment_rate"] = df["comments"] / df["views"] * 100
print(df)

===== YouTube動画データ =====
        video_id                                              title  \
0    zg-m0_aj9i8  【2026東京🇯🇵一日遊推薦】這4個地方，好吃好玩每次都回訪！川越、吉祥寺、鎌倉江之島、高輪...
1    O_enzzD2NTg               【川越 小江戶 懂吃懂玩 全攻略】從東京30分鐘就能抵達 請排入你的行程
2    DT6HBV1DyVE  【日本川越一日遊】 熊野神社「洗錢」增財運 #川越 #小江戶 #日本旅行 #東京近郊 #日本...
3    XYU10ug3gAU  【川越観光_埼玉】小江戸・川越を1日で100%満喫するおすすめ観光プランを紹介！おすすめスポ...
4    E_s1KGpYIZY  比想像中更好玩🇯🇵川越小江戶散策 ✨隨意走進巷弄都是驚喜 ｜百年鰻魚飯、超強蒸蛋布丁、冰川神...
..           ...                                                ...
492  4eDlR46CzU8           4K・ Night walk in Saitama Kawagoe・4K HDR
496  bK_YJALs174  川越達也主廚也太會了!!XD 一定要讓大家看看 鄭智善主廚可愛的一面~ 📺8/29起每週六晚...
497  HCStOt9GEmE                            【埼玉】川越の美味しいデザートスイーツ＆グルメ
498  IWxOVFd2VSM                                埼玉県川越市大正浪漫夢通りライブカメラ
499  F5VZWrzQrjQ                       【川越の旅】小江戸 川越の歩き方／和風スタバと古い街並み

                                           description  \
0    東京旅居～主頻道影片➤https://youtu.be/CbStFOjcWbw\n逛膩了市區...
1    #川越 #小江戶川越 #川越一日遊 #川越冰川神社 #菓子屋橫丁 #吉伊卡哇 #藏造老街 #...
2    • Travel 🚞 川越 •\n\n第一次嚟到有小江戶之稱位於埼玉県嘅「川越」，由西武新宿...
3    小江戸と呼ばれる川越は、江戸の風情を感じられる街並みや歴史的スポット、美味しいグルメが満載の...
4    很多人說，想要看見真正的舊江戶，就得來一次川越。 \n這裡距離東京不到一小時，卻好像被時光遺...
..                                                 ...
492  🕒 07/09 21:40 🌡️ +24℃  🚶‍♂️4km\nI was in Kawag...
496  #川越達也主廚也太會了!!XD\n一定要讓大家看看 #鄭智善 主廚可愛的一面~ 🤩\n想看更...
497  埼玉県川越市にはおいしいスイーツやグルメがたくさんあります。今回はグルメ好き必見の川越の美味...
498  川越市は、埼玉県の北西部に位置し、歴史と伝統、そして現代が見事に融合する、まさに唯一無二の景...
499  #国内旅行 #ひとり旅 #食べ歩き #スターバックス #旅 #VLOG #川越 #SoloT...

                                                  tags          published_at  \
0    東京,東京旅居,東京自由行,東京旅遊,東京必去,東京伴手禮,東京生活花費,東京買房,東京語言...  2026-05-11T12:01:52Z
1                                                       2026-07-25T04:01:15Z
2                                                       2025-04-03T10:05:19Z
3                                                       2025-01-18T04:00:18Z
4                                                       2026-01-04T12:00:21Z
..                                                 ...                   ...
492                     Japan,rambalac,walk,Japan walk  2022-07-17T13:00:12Z
496  食尚玩家,不推怎麼行,食尙玩家歡樂有夠讚,詹姆士,莎莎,時尚玩家,美食,小吃,旅遊,景點,T...  2026-08-07T07:00:30Z
497  旅行の達人,旅行,観光,達人,埼玉 観光,埼玉 観光スポット,埼玉 観光地,埼玉 観光地 川...  2020-02-28T10:45:00Z
498                                                     2026-07-17T10:27:58Z
499  川越,ひとり旅,VLOG,旅,食べ歩き,国内旅行,旅行vlog,旅行,ontheSofa,#...  2020-07-11T14:58:48Z

      views  likes  comments  like_rate  comment_rate
0    106704   1513        44   1.417941      0.041236
1     64362    802        69   1.246077      0.107206
2      4224     46         1   1.089015      0.023674
3    118994    753        43   0.632805      0.036136
4     13485    192        20   1.423804      0.148313
..      ...    ...       ...        ...           ...
492   72617   2424       136   3.338061      0.187284
496    1127     11         0   0.976043      0.000000
497    6535     49         1   0.749809      0.015302
498    1296     21         0   1.620370      0.000000
499    6262     91        22   1.453210      0.351325

[408 rows x 10 columns]

In [ ]:
keywords_cn = {
    "川越": ["川越"],
    "日帰り": ["当天往返"],
    "グルメ": ["美食"],
    "江戸": ["江户"],
    "城": ["城"],
    "寺":["寺"],
    "神社":["神社"],
    "甘薯":["サツマイモ"],
    "着物":["和服"],
    "お菓子":["糖果"],
    "スイーツ":["甜點"],
    "祭り":["节日"],
    "東京":["东京"],
    "観光":["观光"],
    "食べ歩き":["小吃"]
}
results = []

for keyword_jp, keywords in keywords_cn.items():

    condition = False

    for keyword in keywords:
        condition = (
            condition |
            df["title"].str.contains(keyword, na=False, regex=False) |
            df["description"].str.contains(keyword, na=False, regex=False) |
            df["tags"].str.contains(keyword, na=False, regex=False)
        )

    target = df[condition]

    results.append({
        "キーワード": keyword_jp,
        "検索語": ", ".join(keywords),
        "動画本数": len(target),

        "平均再生回数": target["views"].mean(),
        "全体との差（平均再生回数）":
            target["views"].mean() - df["views"].mean(),

        "再生数の中央値": target["views"].median(),
        "全体との差（再生数の中央値）":
            target["views"].median() - df["views"].median(),

        "平均高評価数": target["likes"].mean(),
        "全体との差（平均高評価数）":
            target["likes"].mean() - df["likes"].mean(),

        "平均高評価率": target["like_rate"].mean(),
        "全体との差（平均高評価率）":
            target["like_rate"].mean() - df["like_rate"].mean(),

        "平均コメント率": target["comment_rate"].mean(),
        "全体との差（平均コメント率）":
            target["comment_rate"].mean() - df["comment_rate"].mean()
    })

keyword_df = pd.DataFrame(results)

keyword_df = keyword_df.sort_values(
    "平均再生回数",
    ascending=False
)

keyword_df

,キーワード,検索語,動画本数,平均再生回数,全体との差（平均再生回数）,再生数の中央値,全体との差（再生数の中央値）,平均高評価数,全体との差（平均高評価数）,平均高評価率,全体との差（平均高評価率）,平均コメント率,全体との差（平均コメント率）
8,着物,和服,13,101354.461538,70823.533561,6370.0,2110.0,1732.461538,1260.029405,1.182794,-0.268468,0.056306,-0.092815
9,お菓子,糖果,5,81901.400000,51370.472022,39341.0,35081.0,466.400000,-6.032133,0.836162,-0.615100,0.051038,-0.098083
10,スイーツ,甜點,7,52515.714286,21984.786308,16971.0,12711.0,792.142857,319.710724,1.384532,-0.066730,0.142967,-0.006154
14,食べ歩き,小吃,13,40382.307692,9851.379714,4735.0,475.0,297.230769,-175.201364,0.945522,-0.505740,0.078063,-0.071058
6,神社,神社,136,37102.595588,6571.667610,6751.5,2491.5,534.617647,62.185514,1.460336,0.009074,0.154058,0.004937
2,グルメ,美食,49,33103.428571,2572.500594,9411.0,5151.0,439.428571,-33.003562,1.519831,0.068569,0.174318,0.025197
0,川越,川越,357,30209.899160,-321.028818,4260.0,0.0,470.478992,-1.953141,1.452260,0.000998,0.149013,-0.000108
4,城,城,69,25776.724638,-4754.203340,2812.0,-1448.0,168.985507,-303.446626,1.573076,0.121814,0.111643,-0.037478
7,甘薯,サツマイモ,2,13011.000000,-17519.927978,13011.0,8751.0,191.500000,-280.932133,1.270529,-0.180733,0.027498,-0.121622
5,寺,寺,53,12622.339623,-17908.588355,3174.0,-1086.0,154.264151,-318.167982,1.377484,-0.073779,0.106973,-0.042148
12,東京,东京,4,5132.250000,-25398.677978,1737.0,-2523.0,100.750000,-371.682133,4.622219,3.170957,0.352394,0.203273
11,祭り,节日,2,3367.000000,-27163.927978,3367.0,-893.0,24.500000,-447.932133,0.617309,-0.833953,0.015305,-0.133816
3,江戸,江户,2,522.500000,-30008.427978,522.5,-3737.5,3.500000,-468.932133,0.605030,-0.846233,0.000000,-0.149121
1,日帰り,当天往返,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,観光,观光,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.to_csv("kawagoe_ch.csv", index=False, encoding="utf-8-sig")

In [2]:
result1=[]
result1.append({
        "動画本数": len(df),
        "平均再生回数": df["views"].mean(),
        "再生数の中央値": df["views"].median(),
        "平均高評価数": df["likes"].mean(),
        "平均高評価率": df["like_rate"].mean(),
        "平均コメント率": df["comment_rate"].mean(),
})
df_a=pd.DataFrame(result1)
df_a

   動画本数        平均再生回数  再生数の中央値      平均高評価数    平均高評価率  平均コメント率
0   384  25240.723958   3598.5  414.598958  1.553946  0.16785