In [2]:
import requests
import pandas as pd
API_KEY= 'AIzaSyCHdEgk1wpQtlaY2XJk3kBbh4cqyPNzlMA'

search_url= "https://www.googleapis.com/youtube/v3/search"

search_params={
    "part":"snippet",
    "q":"kawagoe",
    "videoCategoryId":19,
    "type":"video",
    "key":API_KEY,
    "relevanceLanguage":"en",
    "maxResults":50

}
page_token=None
videos=[]
for i in range(10):
 if page_token:
        search_params["pageToken"] = page_token
 response=requests.get(search_url,params=search_params)
 data=response.json()

 video_ids=[]

 for video in data["items"]:
  video_id=video["id"]["videoId"]
  video_ids.append(video_id)

 video_url = "https://www.googleapis.com/youtube/v3/videos"

 video_params={
    "part":"snippet,statistics",
    "id":",".join(video_ids),
    "key":API_KEY
}

 response=requests.get(video_url,params=video_params)
 data_videos=response.json()



 for video in data_videos["items"]:
  video_id=video["id"]

  title=video["snippet"]["title"]
  published_at = video["snippet"]["publishedAt"]
  description= video["snippet"]["description"]
  tags1=video["snippet"].get("tags",[])
  tags=",".join(tags1)

  views = int(video["statistics"].get("viewCount",0))
  likes = int(video["statistics"].get("likeCount",0))
  comments = int(video["statistics"].get("commentCount",0))

  videos.append({
        "video_id": video_id,
        "title": title,
        "description":description,
        "tags":tags,
        "published_at": published_at,
        "views": views,
        "likes": likes,
        "comments": comments
    })
 page_token = data.get("nextPageToken")


df = pd.DataFrame(videos)
df = df.drop_duplicates(subset="video_id")
print("\n===== YouTube動画データ =====")
df["like_rate"] = df["likes"] / df["views"] * 100
df["comment_rate"] = df["comments"] / df["views"] * 100
print(df)

===== YouTube動画データ =====
        video_id                                              title  \
0    uuWL-mXLF7k          Discover Kawagoe: Day Trip to ‘Old Tokyo’
1    GWAUcrJLWIE                     Day trip from Tokyo to Kawagoe
2    Aye3cT7tVyU  Kawagoe: 30 min. from Tokyo. A Day Trip Guide ...
3    SmQGCBErPK8  Just 30mins From Tokyo: KAWAGOE Historic Town ...
4    3gSJshXZYlg  Relaxing Day Trip from Tokyo|A peaceful day tr...
..           ...                                                ...
493  LVoBBHkXFzw                             川越線大宮→川越前面展望2026/08/24
494  YATfTJW8QFA      Kawagoe Saitama Summer Festival. 2026.7.25-26
495  JboUxVp-TTw  คาวะโกเอะ “ของจริง” หรือแค่ฉากนักท่องเที่ยว? |...
496  M-WFlCnnUQ0  Little EDO where FOOD is AMAZING | FIRST time ...
497  OI_ADpl-Sdo  Japan Vlog - Kawagoe Day Trip from Tokyo | Che...

                                           description  \
0    A Day Tripping Guide to Kawagoe: The Little Ed...
1    Read more about this day trip from Tokyo to Ka...
2    Kawagoe is a good day trip destination from To...
3    Looking for a great adventure in Japan? Find h...
4    Hi, I'm Daisuke😊\n\nI took a trip to Kawagoe, ...
..                                                 ...
493                                        E233系10両川越行
494  Kawagoe summer festival million lights is held...
495  คลิปนี้จะพาเดินย่านโกดังดิน (Kurazukuri) ใน Ka...
496  Join me as I explore Kawagoe : Known as Little...
497  In this Japan vlog, I take a relaxing day trip...

                                                  tags          published_at  \
0                                                       2025-01-31T05:23:01Z
1    japan,travel,guide,sightseeing,tourist,japan-g...  2019-03-19T20:14:11Z
2    tokyo travel guide,things to do in Tokyo,itine...  2024-05-16T16:45:01Z
3    japan,japan by food,japanesefood,kawagoe,kawag...  2023-09-18T01:00:12Z
4    japan travel,tokyo travel,tokyo vlog,japan vlo...  2026-05-09T09:00:08Z
..                                                 ...                   ...
493                               川越線,前面展望,E233系,大宮,川越  2026-08-24T09:38:26Z
494                                                     2026-07-26T11:19:20Z
495  ญี่ปุ่น,เที่ยวญี่ปุ่น,คาวะโกเอะ,Kawagoe,Little...  2026-05-03T12:00:24Z
496  japanese food,kawagoe sweets,kawagoe travel,ku...  2024-12-14T10:30:06Z
497  Japan Travel,Japan Trip,Japan Vlog,traveling,H...  2025-04-28T22:00:25Z

      views  likes  comments  like_rate  comment_rate
0    147923   3468        87   2.344463      0.058814
1    246846   4595       157   1.861484      0.063602
2     35828    785        90   2.191024      0.251200
3    145429   3179       176   2.185946      0.121021
4     10710    235        36   2.194211      0.336134
..      ...    ...       ...        ...           ...
493    8423      0         7   0.000000      0.083106
494    5087     29        12   0.570081      0.235895
495   23275    706       107   3.033298      0.459721
496    1636    133         6   8.129584      0.366748
497     584      6         0   1.027397      0.000000

[444 rows x 10 columns]

In [3]:
keywords_en = {
    "川越": ["kawagoe"],
    "日帰り": ["day trip"],
    "江戸": ["edo"],
    "グルメ": ["food"],
    "城": ["castle"],
    "神社": ["shrine"],
    "寺": ["temple"],
    "サツマイモ": ["sweet potato"],
    "着物": ["kimono"],
    "スイーツ": ["sweet"],
    "お菓子": ["candy"],
    "祭り": ["festival"],
    "東京": ["Tokyo"],
    "観光": ["sightseeing"],
    "食べ歩き": ["food walk", "street food", "food tour"]
}

results = []

for keyword_jp, keywords in keywords_en.items():

    condition = False

    for keyword in keywords:
        condition = (
            condition |
            df["title"].str.contains(keyword, na=False, regex=False) |
            df["description"].str.contains(keyword, na=False, regex=False) |
            df["tags"].str.contains(keyword, na=False, regex=False)
        )

    target = df[condition]

    results.append({
        "キーワード": keyword_jp,
        "検索語": ", ".join(keywords),
        "動画本数": len(target),

        "平均再生回数": target["views"].mean(),
        "全体との差（平均再生回数）":
            target["views"].mean() - df["views"].mean(),

        "再生数の中央値": target["views"].median(),
        "全体との差（再生数の中央値）":
            target["views"].median() - df["views"].median(),

        "平均高評価数": target["likes"].mean(),
        "全体との差（平均高評価数）":
            target["likes"].mean() - df["likes"].mean(),

        "平均高評価率": target["like_rate"].mean(),
        "全体との差（平均高評価率）":
            target["like_rate"].mean() - df["like_rate"].mean(),

        "平均コメント率": target["comment_rate"].mean(),
        "全体との差（平均コメント率）":
            target["comment_rate"].mean() - df["comment_rate"].mean()
    })

keyword_df = pd.DataFrame(results)

keyword_df = keyword_df.sort_values(
    "平均再生回数",
    ascending=False
)

keyword_df

,キーワード,検索語,動画本数,平均再生回数,全体との差（平均再生回数）,再生数の中央値,全体との差（再生数の中央値）,平均高評価数,全体との差（平均高評価数）,平均高評価率,全体との差（平均高評価率）,平均コメント率,全体との差（平均コメント率）
12,東京,Tokyo,224,75019.678571,33499.258760,1184.0,539.0,2097.553571,950.468666,3.227348,-0.310019,0.920725,0.034668
7,サツマイモ,sweet potato,39,18112.615385,-23407.804427,1681.0,1036.0,294.051282,-853.033624,3.395487,-0.141880,1.491946,0.605889
13,観光,sightseeing,25,13669.800000,-27850.619811,1532.0,887.0,266.600000,-880.484906,3.480455,-0.056912,0.753868,-0.132189
9,スイーツ,sweet,56,13463.928571,-28056.491240,1349.5,704.5,212.946429,-934.138477,3.314190,-0.223177,1.166781,0.280724
10,お菓子,candy,15,12306.600000,-29213.819811,616.0,-29.0,260.266667,-886.818239,5.408499,1.871132,1.439393,0.553336
14,食べ歩き,"food walk, street food, food tour",46,11685.021739,-29835.398072,1744.5,1099.5,316.347826,-830.737080,3.372683,-0.164684,0.885664,-0.000393
1,日帰り,day trip,122,10587.229508,-30933.190303,1542.0,897.0,216.885246,-930.199660,2.893900,-0.643468,0.818279,-0.067778
2,江戸,edo,142,9599.887324,-31920.532487,954.5,309.5,169.007042,-978.077863,3.329157,-0.208210,1.031518,0.145462
5,神社,shrine,58,9038.534483,-32481.885329,1211.0,566.0,203.586207,-943.498699,3.244513,-0.292854,1.318073,0.432016
4,城,castle,23,8395.304348,-33125.115463,209.0,-436.0,208.086957,-938.997949,3.717693,0.180326,1.051874,0.165817
3,グルメ,food,128,7271.703125,-34248.716686,1283.0,638.0,174.609375,-972.475531,3.369937,-0.167430,0.855162,-0.030895
0,川越,kawagoe,237,7169.156118,-34351.263693,884.0,239.0,149.962025,-997.122880,3.432758,-0.104609,0.832150,-0.053906
8,着物,kimono,18,6983.833333,-34536.586478,743.5,98.5,87.222222,-1059.862683,3.042485,-0.494882,1.580557,0.694500
6,寺,temple,44,5696.204545,-35824.215266,376.0,-269.0,143.227273,-1003.857633,4.016496,0.479129,1.812035,0.925978
11,祭り,festival,31,3324.548387,-38195.871424,1517.0,872.0,79.387097,-1067.697809,2.250441,-1.286926,1.113817,0.227760

In [19]:
keyword_df.to_csv("kawagoe_en.csv", index=False, encoding="utf-8-sig")

In [ ]:
result1=[]
result1.append({
        "動画本数": len(df),
        "平均再生回数": df["views"].mean(),
        "再生数の中央値": df["views"].median(),
        "平均高評価数": df["likes"].mean(),
        "平均高評価率": df["like_rate"].mean(),
        "平均コメント率": df["comment_rate"].mean(),
})
df_a=pd.DataFrame(result1)
df_a

   動画本数       平均再生回数  再生数の中央値      平均高評価数    平均高評価率   平均コメント率
0   414  4398.736715    322.0  100.545894  3.679588  0.799351