In [1]:
import requests
import pandas as pd
API_KEY= ''

search_url= "https://www.googleapis.com/youtube/v3/search"

search_params={
    "part":"snippet",
    "q":"川越",
    "videoCategoryId":19,
    "type":"video",
    "key":API_KEY,
    "relevanceLanguage":"ja",
    "regionCode": "JP",
    "maxResults":50

}
page_token=None
videos=[]
for i in range(10):
 if page_token:
        search_params["pageToken"] = page_token
 response=requests.get(search_url,params=search_params)
 data=response.json()

 video_ids=[]

 for video in data["items"]:
  video_id=video["id"]["videoId"]
  video_ids.append(video_id)

 video_url = "https://www.googleapis.com/youtube/v3/videos"

 video_params={
    "part":"snippet,statistics",
    "id":",".join(video_ids),
    "key":API_KEY
}

 response=requests.get(video_url,params=video_params)
 data_videos=response.json()



 for video in data_videos["items"]:
  video_id=video["id"]

  title=video["snippet"]["title"]
  published_at = video["snippet"]["publishedAt"]
  description= video["snippet"]["description"]
  tags1=video["snippet"].get("tags",[])
  tags=",".join(tags1)

  views = int(video["statistics"].get("viewCount",0))
  likes = int(video["statistics"].get("likeCount",0))
  comments = int(video["statistics"].get("commentCount",0))

  videos.append({
        "video_id": video_id,
        "title": title,
        "description":description,
        "tags":tags,
        "published_at": published_at,
        "views": views,
        "likes": likes,
        "comments": comments
    })
 page_token = data.get("nextPageToken")


df = pd.DataFrame(videos)
df = df.drop_duplicates(subset="video_id")
print("\n===== YouTube動画データ =====")
df["like_rate"] = df["likes"] / df["views"] * 100
df["comment_rate"] = df["comments"] / df["views"] * 100
print(df)

===== YouTube動画データ =====
        video_id                                              title  \
0    Tbp5yDmUX2Q        【川越東武ホテル宿泊記】駅直結で超便利！綺麗な客室と絶品朝食ブッフェを大満喫する一人旅
1    6L0HiZ0GS-g     【4K】2025年11月2日（日）【驚愕】外国人より日本人が殺到！埼玉県川越小江戸が激混み！
2    w7Dj4NVHyng                        【なぜ人気？】小江戸と呼ばれる川越の観光スポットを散策
3    iwBOf4hj9qQ                             【川越】埼玉第3の都市、想像以上に都会だった
4    XYU10ug3gAU  【川越観光_埼玉】小江戸・川越を1日で100%満喫するおすすめ観光プランを紹介！おすすめスポ...
..           ...                                                ...
445  jAt7ZhFrq0s                          『川越』妖怪まち歩き見た後、駄菓子屋横丁へ【4K】
446  nudo4BYehCI                      【川越水上公園】造波プールに主がいた【プールフィッシング】
447  xVkUUvKQ6Fg  Chiikawa Mogumogu Honpo Kawagoe Store (ちいかわもぐも...
448  hqAkIlBb7Sk                                埼玉県川越市大正浪漫夢通りライブカメラ
449  j_ZYFthwqRc                            【川越氷川神社】 縁むすび風鈴 #shorts

                                           description  \
0    今回は、埼玉県川越市にある「川越東武ホテル」の宿泊記をお届けします。\n最安値をチェック\n...
1    #埼玉\n#川越市 \n#小江戸川越 \n#小江戸\n#埼玉観光\n#埼玉旅行\n#旅行\n...
2    川越は古い土蔵造りが並ぶ一番街の素晴らしい景観や氷川神社などが多くの観光客を惹き付けています...
3    埼玉県川越市 川越駅西口を散策。\n観光地として有名な川越のメインエリアとは反対側にある西口...
4    小江戸と呼ばれる川越は、江戸の風情を感じられる街並みや歴史的スポット、美味しいグルメが満載の...
..                                                 ...
445  東京 新宿から1時間弱\n凄くリラックスできる街並みの\n川越で懐かしいくもマニアックな体験...
446  動画だとわかりずらいですが思った以上にでかい！\n造波プールには大物がいますので楽しんでくだ...
447  The second branch of "Chiikawa Mogumogu Honpo,...
448  川越市は、埼玉県の北西部に位置し、歴史と伝統、そして現代が見事に融合する、まさに唯一無二の景...
449  約2,000個の江戸風鈴が涼しげな音色を奏でる🎐✨\n\n「川越氷川神社 縁むすび風鈴」が9...

                                                  tags          published_at  \
0    川越東武ホテル,川越,ホテル,宿泊記,一人旅,朝食,ブッフェ,U_PLACE,埼玉観光,小江...  2026-05-31T06:07:15Z
1    #埼玉,#川越市,#小江戸川越,#小江戸,#埼玉観光,#埼玉旅行,#旅行,#観光,#日本,#...  2025-11-07T10:00:08Z
2    旅行,観光,川越　観光,川越　旅行,埼玉県,川越,蔵の街,川越　一番街,重伝建,重要伝統的建...  2024-08-17T00:15:05Z
3                                                       2026-01-17T03:00:06Z
4                                                       2025-01-18T04:00:18Z
..                                                 ...                   ...
445                                                     2025-07-06T00:28:44Z
446                                                     2022-11-26T04:01:36Z
447                                                     2025-03-22T03:01:00Z
448                                                     2026-07-24T10:40:52Z
449                                                     2026-08-27T11:00:12Z

      views  likes  comments  like_rate  comment_rate
0       868     10         0   1.152074      0.000000
1     15872    129         0   0.812752      0.000000
2    107963    563        37   0.521475      0.034271
3      1156     25         0   2.162630      0.000000
4    118994    753        43   0.632805      0.036136
..      ...    ...       ...        ...           ...
445    1661      7         7   0.421433      0.421433
446    8647     40         2   0.462588      0.023129
447    1391     27         0   1.941050      0.000000
448    1578     12         0   0.760456      0.000000
449    1255      5         0   0.398406      0.000000

[366 rows x 10 columns]

In [3]:
keywords = [
    "川越",
    "日帰り",
    "江戸",
    "グルメ",
    "城",
    "神社",
    "寺",
    "サツマイモ",
    "着物",
    "スイーツ",
    "菓子",
    "東京",
    "祭り",
    "食べ歩き",
    "観光"
]

results = []

for keyword in keywords:

    condition = (
        df["title"].str.contains(keyword, na=False) |
        df["description"].str.contains(keyword, na=False) |
        df["tags"].str.contains(keyword, na=False)
    )

    target = df[condition]

    results.append({
        "キーワード": keyword,
        "動画本数": len(target),
        "平均再生回数": target["views"].mean(),
        "全体との差（平均再生回数）":target["views"].mean()-df["views"].mean(),
        "再生数の中央値": target["views"].median(),
        "全体との差（再生数の中央値）":target["views"].median()-df["views"].median(),
        "平均高評価数": target["likes"].mean(),
        "全体との差（平均高評価数）":target["likes"].mean()-df["likes"].mean(),
        "平均高評価率": target["like_rate"].mean(),
        "全体との差（平均高評価率）":target["like_rate"].mean()-df["like_rate"].mean(),
        "平均コメント率": target["comment_rate"].mean(),
        "全体との差（平均コメント率）": target["comment_rate"].mean()-df["comment_rate"].mean()
    })

keyword_df = pd.DataFrame(results)

keyword_df = keyword_df.sort_values(
    "平均再生回数",
    ascending=False
)

keyword_df

,キーワード,動画本数,平均再生回数,全体との差（平均再生回数）,再生数の中央値,全体との差（再生数の中央値）,平均高評価数,全体との差（平均高評価数）,平均高評価率,全体との差（平均高評価率）,平均コメント率,全体との差（平均コメント率）
8,着物,9,230450.555556,203075.376417,35491.0,31993.0,4535.000000,4155.224490,1.628309,0.419764,0.016376,-0.125193
13,食べ歩き,79,53996.215190,26621.036052,6663.0,3165.0,1027.772152,647.996642,1.343421,0.134876,0.123871,-0.017698
11,東京,65,53869.092308,26493.913169,18733.0,15235.0,517.446154,137.670644,1.316048,0.107503,0.166271,0.024702
3,グルメ,100,42341.480000,14966.300862,6598.5,3100.5,728.230000,348.454490,1.228074,0.019529,0.157984,0.016415
5,神社,122,42024.663934,14649.484796,6756.0,3258.0,607.672131,227.896621,1.380360,0.171815,0.155878,0.014309
14,観光,154,37853.396104,10478.216966,5738.5,2240.5,685.220779,305.445269,1.193042,-0.015503,0.131703,-0.009866
0,川越,437,27579.226545,204.047406,3524.0,26.0,382.560641,2.785131,1.198665,-0.009880,0.141856,0.000287
4,城,76,22807.302632,-4567.876507,1410.0,-2088.0,143.289474,-236.486037,1.392887,0.184342,0.086994,-0.054575
10,菓子,61,22542.704918,-4832.474220,8818.0,5320.0,192.803279,-186.972232,1.228752,0.020207,0.139259,-0.002310
1,日帰り,28,21438.785714,-5936.393424,8161.5,4663.5,278.607143,-101.168367,1.137207,-0.071339,0.119676,-0.021893
2,江戸,196,19727.341837,-7647.837302,4008.5,510.5,251.193878,-128.581633,1.244494,0.035949,0.118951,-0.022618
9,スイーツ,22,16239.272727,-11135.906411,4895.5,1397.5,136.454545,-243.320965,1.138815,-0.069730,0.104504,-0.037065
12,祭り,36,9921.472222,-17453.706916,2806.5,-691.5,118.638889,-261.136621,1.743193,0.534648,0.128357,-0.013211
7,サツマイモ,3,9827.666667,-17547.512472,3470.0,-28.0,135.000000,-244.775510,1.058529,-0.150016,0.018339,-0.123230
6,寺,65,8600.876923,-18774.302215,1051.0,-2447.0,106.307692,-273.467818,1.327733,0.119188,0.067449,-0.074120

In [4]:
keyword_df.to_csv("kawagoe_ja.csv", index=False, encoding="utf-8-sig")

In [7]:
result1=[]
result1.append({
        "動画本数": len(df),
        "平均再生回数": df["views"].mean(),
        "再生数の中央値": df["views"].median(),
        "平均高評価数": df["likes"].mean(),
        "平均高評価率": df["like_rate"].mean(),
        "平均コメント率": df["comment_rate"].mean(),
})
df_a=pd.DataFrame(result1)
df_a

   動画本数        平均再生回数  再生数の中央値      平均高評価数    平均高評価率   平均コメント率
0   366  29242.142077   3361.5  430.631148  1.269144  0.130009